# -*- coding: utf-8 -*-
"""Audio_CV_1to1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JZ-nKjx-9parqCd_jgZjnecGCT8WMXP5
"""

import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import GradientBoostingClassifier
from xgboost import XGBClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import classification_report, ConfusionMatrixDisplay, log_loss
from sklearn.model_selection import StratifiedKFold
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.optimizers import Adam
import pickle
import math
import re
from collections import defaultdict

try:
    from google.colab import drive
    drive.mount('/content/drive')
except Exception:
    pass

mfcc_df = pd.read_csv("/content/drive/MyDrive/Project Data/audio/audio_chunks/chunks_metadata_with_mfcc.csv")
mfcc_df

# video_feat_path = "/content/drive/MyDrive/Project Data/cv_features/fc1_fc2_features_frame.pkl"
# video_feats = np.load(video_feat_path, allow_pickle=True).item()

mfcc_df = mfcc_df[mfcc_df["subfolder_audio"].isin(["passage_1", "passage_2", "passage_3"])]

mfcc_cols = [c for c in mfcc_df.columns if c.startswith("mfcc")]

frame_feat_path = "/content/drive/MyDrive/Project Data/cv_features/fc1_fc2_features_frame.pkl"
with open(frame_feat_path, "rb") as f:
    frame_feats = pickle.load(f)

for group, subj_dict in list(frame_feats.items())[:1]:  # first group
    print("Group:", group)
    for subj, passages in list(subj_dict.items())[:2]:  # first 2 subjects
        print(" Subject:", subj)
        for passage, arr in passages.items():
            print(f"   {passage} -> shape {arr.shape}")

# # Normalize audio IDs
# mfcc_df["participant_id"] = mfcc_df["participant_id"].apply(normalize_subject_id)

# # Normalize video IDsqq
# normalized_frame_feats = {}
# for group, subjects in frame_feats.items():
#     normalized_frame_feats[group] = {}
#     for pid, passages in subjects.items():
#         new_pid = normalize_subject_id(pid)
#         normalized_frame_feats[group][new_pid] = passages

# frame_feats = normalized_frame_feats

# import re

# def normalize_id(pid: str) -> str:
#     # replace dash with dot in dates
#     pid = pid.replace("-", ".")
#     # turn (1), (2) into _1, _2
#     pid = re.sub(r"\((\d+)\)", r"_\1", pid)
#     # fix cases like "033_2025_03.26" → "033_2025.03.26"
#     pid = re.sub(r"(\d{4})_(\d{2}\.\d{2})", r"\1.\2", pid)
#     return pid

# # apply normalization
# audio_subjects_norm = {normalize_id(s) for s in audio_subjects}
# video_subjects_norm = {normalize_id(s) for s in video_subjects}

# overlap = audio_subjects_norm & video_subjects_norm
# print("Normalized overlap:", len(overlap))
# print(sorted(list(overlap))[:20])
# print("\nStill only in audio:", audio_subjects_norm - video_subjects_norm)
# print("\nStill only in video:", video_subjects_norm - audio_subjects_norm)

DEFAULT_CHUNK_SEC = 15


try:
    normalize_pid = normalize_subject_id
except NameError:
    def normalize_pid(s):
        s = str(s)

        s = s.replace('-', '_').replace('(', '_').replace(')', '_').replace('.', '_')
        s = re.sub(r'[_\s]+', '_', s).strip('_')
        return s

frame_map = {}
for group, subjects in frame_feats.items():
    frame_map[group] = {}
    for orig_key in subjects.keys():
        nid = normalize_pid(orig_key).lower()
        frame_map[group][nid] = orig_key

skipped_no_subject = 0
skipped_no_passage = 0
skipped_zero_len = 0
skipped_subjects = set()
skipped_passages = set()

aligned_audio, aligned_video, aligned_labels, aligned_subjects, aligned_passages = [], [], [], [], []

for idx, row in mfcc_df.iterrows():
    raw_pid = row["participant_id"]
    pid_norm = normalize_pid(raw_pid).lower()
    passage = row["subfolder_audio"]

    seg_idx = None
    if "segment_index" in row and not pd.isna(row["segment_index"]):
        try:
            seg_idx = int(row["segment_index"])
        except Exception:
            seg_idx = int(float(row["segment_index"]))
    else:
        seg_idx = 1

    if "duration" in row and not pd.isna(row["duration"]):
        try:
            chunk_dur = max(1, int(round(float(row["duration"]))))
        except Exception:
            chunk_dur = DEFAULT_CHUNK_SEC
    else:
        chunk_dur = DEFAULT_CHUNK_SEC

    raw_label = row.get("label", "")
    if isinstance(raw_label, str) and raw_label:
        group = "control" if ("control" in raw_label.lower() or "negative" in raw_label.lower()) else "experimental"
    else:
        group = "control" if "control" in str(raw_pid).lower() else "experimental"

    if pid_norm not in frame_map.get(group, {}):
        skipped_no_subject += 1
        skipped_subjects.add(raw_pid)
        continue
    orig_subj_key = frame_map[group][pid_norm]

    if passage not in frame_feats[group][orig_subj_key]:
        skipped_no_passage += 1
        skipped_passages.add((raw_pid, passage))
        continue

    video_arr = frame_feats[group][orig_subj_key][passage]
    video_len = video_arr.shape[0]

    # compute chunk frame indices inside the passage using segment_index
    # segment_index is 1-based: first chunk -> frames [0:chunk_dur], second -> [chunk_dur:2*chunk_dur], etc.
    chunk_start = (seg_idx - 1) * chunk_dur
    # clamp start to reasonable range: prefer exact chunk but if start is beyond passage, snap to last chunk window
    if chunk_start >= video_len:
        # place chunk at the tail of the passage (take last chunk_dur seconds)
        chunk_start = max(0, video_len - chunk_dur)
    chunk_end = min(chunk_start + chunk_dur, video_len)

    if chunk_end <= chunk_start:
        skipped_zero_len += 1
        continue

    video_chunk = video_arr[chunk_start:chunk_end]
    if video_chunk.shape[0] == 0:
        skipped_zero_len += 1
        continue

    video_feat = video_chunk.mean(axis=0)

    audio_feat = row[mfcc_cols].values.astype(float)

    label_raw = row.get("label", "")
    if isinstance(label_raw, str) and label_raw:
        lab = 0 if ("control" in label_raw.lower() or "negative" in label_raw.lower()) else 1
    else:
        lab = 0 if group == "control" else 1

    aligned_audio.append(audio_feat)
    aligned_video.append(video_feat)
    aligned_labels.append(lab)
    aligned_subjects.append(orig_subj_key)
    aligned_passages.append(passage)

# Convert to arrays
aligned_audio = np.array(aligned_audio)
aligned_video = np.array(aligned_video)
aligned_labels = np.array(aligned_labels)
aligned_subjects = np.array(aligned_subjects)
aligned_passages = np.array(aligned_passages)

print("Audio chunks:", aligned_audio.shape)
print("Video chunks:", aligned_video.shape)
print("Labels:", aligned_labels.shape)
print("Unique subjects:", len(np.unique(aligned_subjects)))
print("Example subject:", aligned_subjects[0], "Passage:", aligned_passages[0])
print("MFCC example shape:", aligned_audio[0].shape)
print("Video example shape:", aligned_video[0].shape)

print("\nSkipped summary:")
print(" - missing subject matches:", skipped_no_subject)
print(" - missing passage in video:", skipped_no_passage)
print(" - zero-length video chunk after clipping:", skipped_zero_len)

print("Examples missing subjects (up to 10):", list(skipped_subjects)[:10])
print("Examples missing passage entries (up to 10):", list(skipped_passages)[:10])

# Create a DataFrame to explore alignment
aligned_df = pd.DataFrame({
    "subject": aligned_subjects,
    "passage": aligned_passages,
    "label": aligned_labels
})

print(aligned_df.head())
print("\nSubjects:", aligned_df["subject"].nunique())
print("Passages per subject:\n", aligned_df.groupby("subject")["passage"].nunique())

# Example feature shapes
print("\nAudio features shape:", aligned_audio.shape)   # (1036, 13)
print("Video features shape:", aligned_video.shape)     # (1036, 8192)

idx = 0
print("Subject:", aligned_subjects[idx])
print("Passage:", aligned_passages[idx])
print("Label:", aligned_labels[idx])
print("Audio features:", aligned_audio[idx])
print("Video features (first 10 dims):", aligned_video[idx][:10])

subjects = np.unique(aligned_subjects)
labels_by_subject = []

for subj in subjects:
    subj_mask = aligned_subjects == subj
    labels_by_subject.append(int(np.round(aligned_labels[subj_mask].mean())))

labels_by_subject = np.array(labels_by_subject)

# Split subjects instead of samples
train_subjects, test_subjects = train_test_split(
    subjects, test_size=0.2, stratify=labels_by_subject, random_state=42
)

print("Train subjects:", len(train_subjects))
print("Test subjects:", len(test_subjects))

# --- Build train/test splits ---
train_mask = np.isin(aligned_subjects, train_subjects)
test_mask = np.isin(aligned_subjects, test_subjects)

X_audio_train, X_audio_test = aligned_audio[train_mask], aligned_audio[test_mask]
X_video_train, X_video_test = aligned_video[train_mask], aligned_video[test_mask]
y_train, y_test = aligned_labels[train_mask], aligned_labels[test_mask]

# Normalize separately (avoid test leakage)
scaler_audio = StandardScaler()
scaler_video = StandardScaler()

X_audio_train = scaler_audio.fit_transform(X_audio_train)
X_audio_test = scaler_audio.transform(X_audio_test)

X_video_train = scaler_video.fit_transform(X_video_train)
X_video_test = scaler_video.transform(X_video_test)

# Concatenate for multimodal
X_train = np.concatenate([X_audio_train, X_video_train], axis=1)
X_test = np.concatenate([X_audio_test, X_video_test], axis=1)

print("Final train samples:", X_train.shape, "test samples", X_test.shape)

SAVE_DIR = "/content/drive/MyDrive/Prject Data/multimodal_dataset_v1"
os.makedirs(SAVE_DIR, exist_ok=True)

np.savez(
    os.path.join(SAVE_DIR, "data.npz"),
    X_train=X_train,
    X_test=X_test,
    y_train=y_train,
    y_test=y_test,
    train_subjects=train_subjects,
    test_subjects=test_subjects,
)

import joblib

joblib.dump(scaler_audio, os.path.join(SAVE_DIR, "scaler_audio.pkl"))
joblib.dump(scaler_video, os.path.join(SAVE_DIR, "scaler_video.pkl"))

metadata = {
    "audio_dim": X_audio_train.shape[1],
    "video_dim": X_video_train.shape[1],
    "random_state": 42,
    "split_by": "subject",
    "modalities": ["audio", "video"]
}

joblib.dump(metadata, os.path.join(SAVE_DIR, "metadata.pkl"))

data = np.load("/content/drive/MyDrive/Project Data/multimodal_dataset_v1/data.npz")

X_train = data["X_train"]
X_test = data["X_test"]
y_train = data["y_train"]
y_test = data["y_test"]
train_subjects = data["train_subjects"]
test_subjects = data["test_subjects"]

scaler_audio = joblib.load("/content/drive/MyDrive/Project Data/multimodal_dataset_v1/scaler_audio.pkl")
scaler_video = joblib.load("/content/drive/MyDrive/Project Data/multimodal_dataset_v1/scaler_video.pkl")





"""## Visualization

"""

import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.decomposition import PCA
import umap.umap_ as umap

# --- Basic metadata / distribution plots ---
plt.figure(figsize=(6,4))
aligned_df["label"].value_counts().plot(kind="bar")
plt.title("Class Distribution (0=Control, 1=Experimental)")
plt.show()

plt.figure(figsize=(10,4))
aligned_df["subject"].value_counts().sort_values(ascending=False).plot(kind="bar")
plt.title("Samples per Subject")
plt.tight_layout()
plt.show()

plt.figure(figsize=(6,4))
aligned_df["passage"].value_counts().plot(kind="bar")
plt.title("Samples per Passage")
plt.show()

# --- PCA for Audio Features ---
pca_audio = PCA(n_components=2)
audio_2d = pca_audio.fit_transform(aligned_audio)

plt.figure(figsize=(6,5))
sns.scatterplot(x=audio_2d[:,0], y=audio_2d[:,1], hue=aligned_labels, palette="coolwarm", s=20)
plt.title("Audio MFCC PCA (2D)")
plt.xlabel("PC1")
plt.ylabel("PC2")
plt.legend(title="class", loc="best")
plt.show()

# --- PCA for Video Features ---
pca_video = PCA(n_components=2)
video_2d = pca_video.fit_transform(aligned_video)

plt.figure(figsize=(6,5))
sns.scatterplot(x=video_2d[:,0], y=video_2d[:,1], hue=aligned_labels, palette="coolwarm", s=20)
plt.title("Video Feature PCA (2D)")
plt.xlabel("PC1")
plt.ylabel("PC2")
plt.legend(title="class")
plt.show()

# --- PCA for Combined Multimodal ---
combined = np.concatenate([aligned_audio, aligned_video], axis=1)
pca_mm = PCA(n_components=2)
mm_2d = pca_mm.fit_transform(combined)

plt.figure(figsize=(6,5))
sns.scatterplot(x=mm_2d[:,0], y=mm_2d[:,1], hue=aligned_labels, palette="coolwarm", s=20)
plt.title("Multimodal PCA (Audio + Video)")
plt.xlabel("PC1")
plt.ylabel("PC2")
plt.legend(title="class")
plt.show()

# --- UMAP for richer embedding ---
reducer = umap.UMAP(n_neighbors=20, min_dist=0.1, metric="euclidean")
umap_2d = reducer.fit_transform(combined)

plt.figure(figsize=(6,5))
sns.scatterplot(x=umap_2d[:,0], y=umap_2d[:,1], hue=aligned_labels, palette="coolwarm", s=20)
plt.title("UMAP Embedding of Multimodal Features")
plt.xlabel("UMAP1")
plt.ylabel("UMAP2")
plt.legend(title="class")
plt.show()

# --- Visualize train/test subject split ---
train_subj_set = set(train_subjects)
split_colors = ["train" if s in train_subj_set else "test" for s in aligned_subjects]

plt.figure(figsize=(10,4))
pd.Series(split_colors, name="dataset").value_counts().plot(kind="bar")
plt.title("Train/Test Split")
plt.show()

plt.figure(figsize=(12,4))
sns.scatterplot(x=mm_2d[:,0], y=mm_2d[:,1], hue=split_colors, palette=["green","purple"], s=20)
plt.title("Train/Test Split in Multimodal PCA Space")
plt.xlabel("PC1")
plt.ylabel("PC2")
plt.show()

"""## Model training"""

models = {
    "Logistic Regression": LogisticRegression(max_iter=1, warm_start=True, solver="saga"),
    "Gradient Boosting": GradientBoostingClassifier(n_estimators=50, warm_start=True),
    "XGBoost": XGBClassifier(use_label_encoder=False, eval_metric="logloss", n_estimators=50),
    "Naive Bayes": GaussianNB(),
    "DNN": MLPClassifier(hidden_layer_sizes=(64, 32), max_iter=1, warm_start=True)
}

n_epochs = 20
histories = {}

for name, model in models.items():
    print(f"\nTraining {name} ...")
    history = {"train_loss": [], "val_loss": [], "train_acc": [], "val_acc": []}

    for epoch in range(n_epochs):
        if name == "Naive Bayes":

            model.fit(X_train, y_train)
        else:
            model.fit(X_train, y_train)

        y_train_pred = model.predict(X_train)
        y_val_pred = model.predict(X_test)

        if hasattr(model, "predict_proba"):
            train_loss = log_loss(y_train, model.predict_proba(X_train))
            val_loss = log_loss(y_test, model.predict_proba(X_test))
        else:
            train_loss = np.nan
            val_loss = np.nan

        train_acc = np.mean(y_train_pred == y_train)
        val_acc = np.mean(y_val_pred == y_test)

        history["train_loss"].append(train_loss)
        history["val_loss"].append(val_loss)
        history["train_acc"].append(train_acc)
        history["val_acc"].append(val_acc)

        print(f"Epoch {epoch+1}/{n_epochs} - "
              f"train_acc: {train_acc:.3f}, val_acc: {val_acc:.3f}, "
              f"train_loss: {train_loss:.3f}, val_loss: {val_loss:.3f}")

    histories[name] = history

    # Evaluation
    y_pred = model.predict(X_test)
    print(f"\n{name} Classification Report (video-only, chunk-level):\n")
    print(classification_report(y_test, y_pred))

    fig, ax = plt.subplots(figsize=(5, 5))
    disp = ConfusionMatrixDisplay.from_predictions(y_test, y_pred, ax=ax)
    disp.ax_.set_title(name + " (video-only, chunk-level)")
    plt.show()

    # Plot
    plt.figure(figsize=(10, 4))
    plt.subplot(1, 2, 1)
    plt.plot(history["train_acc"], label="train_acc")
    plt.plot(history["val_acc"], label="val_acc")
    plt.title(name + " Accuracy")
    plt.xlabel("Epoch")
    plt.ylabel("Accuracy")
    plt.legend()

    plt.subplot(1, 2, 2)
    plt.plot(history["train_loss"], label="train_loss")
    plt.plot(history["val_loss"], label="val_loss")
    plt.title(name + " Loss")
    plt.xlabel("Epoch")
    plt.ylabel("Log Loss")
    plt.legend()

    plt.suptitle(name + " Training History")
    plt.show()

models = {
    "DNN": MLPClassifier(
        hidden_layer_sizes=(128, 64, 32),
        alpha=1e-3,
        max_iter=1,
        warm_start=True,
        early_stopping=True,
        n_iter_no_change=5,
        validation_fraction=0.2,
        random_state=42
    )
}


n_epochs = 20
histories = {}

for name, model in models.items():
    print(f"\nTraining {name} ...")
    history = {"train_loss": [], "val_loss": [], "train_acc": [], "val_acc": []}

    for epoch in range(n_epochs):
        if name == "Naive Bayes":

            model.fit(X_train, y_train)
        else:
            model.fit(X_train, y_train)

        y_train_pred = model.predict(X_train)
        y_val_pred = model.predict(X_test)

        if hasattr(model, "predict_proba"):
            train_loss = log_loss(y_train, model.predict_proba(X_train))
            val_loss = log_loss(y_test, model.predict_proba(X_test))
        else:
            train_loss = np.nan
            val_loss = np.nan

        train_acc = np.mean(y_train_pred == y_train)
        val_acc = np.mean(y_val_pred == y_test)

        history["train_loss"].append(train_loss)
        history["val_loss"].append(val_loss)
        history["train_acc"].append(train_acc)
        history["val_acc"].append(val_acc)

        print(f"Epoch {epoch+1}/{n_epochs} - "
              f"train_acc: {train_acc:.3f}, val_acc: {val_acc:.3f}, "
              f"train_loss: {train_loss:.3f}, val_loss: {val_loss:.3f}")

    histories[name] = history

    # Evaluation
    y_pred = model.predict(X_test)
    print(f"\n{name} Classification Report (video-only, chunk-level):\n")
    print(classification_report(y_test, y_pred))

    fig, ax = plt.subplots(figsize=(5, 5))
    disp = ConfusionMatrixDisplay.from_predictions(y_test, y_pred, ax=ax)
    disp.ax_.set_title(name + " (video-only, chunk-level)")
    plt.show()

    # Plot
    plt.figure(figsize=(10, 4))
    plt.subplot(1, 2, 1)
    plt.plot(history["train_acc"], label="train_acc")
    plt.plot(history["val_acc"], label="val_acc")
    plt.title(name + " Accuracy")
    plt.xlabel("Epoch")
    plt.ylabel("Accuracy")
    plt.legend()

    plt.subplot(1, 2, 2)
    plt.plot(history["train_loss"], label="train_loss")
    plt.plot(history["val_loss"], label="val_loss")
    plt.title(name + " Loss")
    plt.xlabel("Epoch")
    plt.ylabel("Log Loss")
    plt.legend()

    plt.suptitle(name + " Training History")
    plt.show()

import torch
import torch.nn as nn
import torch.optim as optim
from sklearn.metrics import classification_report, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

# ---- Models ----
class MultimodalNet(nn.Module):
    def __init__(self, input_dim, hidden_dims=[128, 64, 32], dropout=0.6):
        super().__init__()
        layers = []
        prev_dim = input_dim
        for h in hidden_dims:
            layers.append(nn.Linear(prev_dim, h))
            layers.append(nn.ReLU())
            layers.append(nn.Dropout(dropout))
            layers.append(nn.ReLU())
            layers.append(nn.Dropout(dropout))
            prev_dim = h
        layers.append(nn.Linear(prev_dim, 2))
        self.net = nn.Sequential(*layers)

    def forward(self, x):
        return self.net(x)


# Logistic Regression (with weight decay for regularization)
class LogisticRegressionModel(nn.Module):
    def __init__(self, input_dim):
        super().__init__()
        self.linear = nn.Linear(input_dim, 2)

    def forward(self, x):
        return self.linear(x)


# RNN
class RNNClassifier(nn.Module):
    def __init__(self, input_dim, hidden_dim=64, num_layers=2, dropout=0.5):
        super().__init__()
        self.rnn = nn.RNN(input_dim, hidden_dim, num_layers=num_layers,
                          batch_first=True, dropout=dropout)
        self.fc = nn.Linear(hidden_dim, 2)

    def forward(self, x):
        x = x.unsqueeze(-1)  # [batch, input_dim, 1]
        out, _ = self.rnn(x)
        return self.fc(out[:, -1, :])


# LSTM
class LSTMClassifier(nn.Module):
    def __init__(self, input_dim, hidden_dim=64, num_layers=2, dropout=0.5):
        super().__init__()
        self.lstm = nn.LSTM(input_dim, hidden_dim, num_layers=num_layers,
                            batch_first=True, dropout=dropout)
        self.fc = nn.Linear(hidden_dim, 2)

    def forward(self, x):
        x = x.unsqueeze(-1)  # [batch, input_dim, 1]
        out, _ = self.lstm(x)
        return self.fc(out[:, -1, :])


# Data
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
X_train_t = torch.tensor(X_train, dtype=torch.float32).to(device)
y_train_t = torch.tensor(y_train, dtype=torch.long).to(device)
X_test_t  = torch.tensor(X_test, dtype=torch.float32).to(device)
y_test_t  = torch.tensor(y_test, dtype=torch.long).to(device)

# Models List
models = {
    "DNN": MultimodalNet(input_dim=X_train.shape[1]).to(device),
    "LogReg": LogisticRegressionModel(input_dim=X_train.shape[1]).to(device),
    "RNN": RNNClassifier(input_dim=1, hidden_dim=64).to(device),   # treat feature dim as seq_len
    "LSTM": LSTMClassifier(input_dim=1, hidden_dim=64).to(device)
}

n_epochs = 20
batch_size = 32
histories = {}

for name, model in models.items():
    print(f"\nTraining {name} ...")
    history = {"train_loss": [], "val_loss": [], "train_acc": [], "val_acc": []}

    criterion = nn.CrossEntropyLoss()
    # Logistic regression with decay
    if name == "LogReg":
        optimizer = optim.Adam(model.parameters(), lr=1e-3, weight_decay=1e-2)
    else:
        optimizer = optim.Adam(model.parameters(), lr=1e-3, weight_decay=1e-4)

    for epoch in range(n_epochs):

        model.train()
        permutation = torch.randperm(X_train_t.size(0))
        epoch_loss, correct = 0, 0

        for i in range(0, X_train_t.size(0), batch_size):
            idx = permutation[i:i+batch_size]
            batch_x, batch_y = X_train_t[idx], y_train_t[idx]

            optimizer.zero_grad()
            outputs = model(batch_x)
            loss = criterion(outputs, batch_y)
            loss.backward()
            optimizer.step()

            epoch_loss += loss.item() * batch_x.size(0)
            correct += (outputs.argmax(1) == batch_y).sum().item()

        train_loss = epoch_loss / len(X_train_t)
        train_acc = correct / len(X_train_t)

        # Validation
        model.eval()
        with torch.no_grad():
            outputs = model(X_test_t)
            val_loss = criterion(outputs, y_test_t).item()
            val_acc = (outputs.argmax(1) == y_test_t).float().mean().item()

        history["train_loss"].append(train_loss)
        history["val_loss"].append(val_loss)
        history["train_acc"].append(train_acc)
        history["val_acc"].append(val_acc)

        print(f"Epoch {epoch+1}/{n_epochs} - "
              f"train_acc: {train_acc:.3f}, val_acc: {val_acc:.3f}, "
              f"train_loss: {train_loss:.3f}, val_loss: {val_loss:.3f}")

    histories[name] = history

    # Evaluation
    y_pred = outputs.argmax(1).cpu().numpy()
    print(f"\n{name} Classification Report (video+audio, chunk-level):\n")
    print(classification_report(y_test, y_pred))

    fig, ax = plt.subplots(figsize=(5, 5))
    ConfusionMatrixDisplay.from_predictions(y_test, y_pred, ax=ax)
    ax.set_title(name + " (video+audio, chunk-level)")
    plt.show()

    # Plot the graphs
    plt.figure(figsize=(10, 4))
    plt.subplot(1, 2, 1)
    plt.plot(history["train_acc"], label="train_acc")
    plt.plot(history["val_acc"], label="val_acc")
    plt.title(name + " Accuracy")
    plt.xlabel("Epoch")
    plt.ylabel("Accuracy")
    plt.legend()

    plt.subplot(1, 2, 2)
    plt.plot(history["train_loss"], label="train_loss")
    plt.plot(history["val_loss"], label="val_loss")
    plt.title(name + " Loss")
    plt.xlabel("Epoch")
    plt.ylabel("Log Loss")
    plt.legend()

    plt.suptitle(name + " Training History")
    plt.show()

import torch
import torch.nn as nn
import torch.optim as optim
from sklearn.metrics import classification_report, ConfusionMatrixDisplay, log_loss
from sklearn.linear_model import LogisticRegression
import numpy as np
import matplotlib.pyplot as plt

# DNN
class MultimodalNet(nn.Module):
    def __init__(self, input_dim, hidden_dims=[128, 64, 32], dropout=0.5):
        super().__init__()
        layers = []
        prev_dim = input_dim
        for h in hidden_dims:
            layers.append(nn.Linear(prev_dim, h))
            layers.append(nn.ReLU())
            layers.append(nn.Dropout(dropout))
            layers.append(nn.ReLU())
            layers.append(nn.Dropout(dropout))
            prev_dim = h
        layers.append(nn.Linear(prev_dim, 2))
        self.net = nn.Sequential(*layers)

    def forward(self, x):
        return self.net(x)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
X_train_t = torch.tensor(X_train, dtype=torch.float32).to(device)
y_train_t = torch.tensor(y_train, dtype=torch.long).to(device)
X_test_t  = torch.tensor(X_test, dtype=torch.float32).to(device)
y_test_t  = torch.tensor(y_test, dtype=torch.long).to(device)

# Models list
models = {
    "DNN": MultimodalNet(input_dim=X_train.shape[1]).to(device),
    "LogReg_L2(Ridge)": LogisticRegression(
        penalty="l2", solver="lbfgs", C=1.0, max_iter=1000
    ),
    "LogReg_L1(Lasso)": LogisticRegression(
        penalty="l1", solver="saga", C=1.0, max_iter=1000
    )
}

n_epochs = 20
batch_size = 32
histories = {}

for name, model in models.items():
    print(f"\nTraining {name} ...")
    history = {"train_loss": [], "val_loss": [], "train_acc": [], "val_acc": []}

    if name == "DNN":
        # PyTorch training loop
        criterion = nn.CrossEntropyLoss()
        optimizer = optim.Adam(model.parameters(), lr=1e-3, weight_decay=1e-4)  # L2

        for epoch in range(n_epochs):

            model.train()
            permutation = torch.randperm(X_train_t.size(0))
            epoch_loss, correct = 0, 0

            for i in range(0, X_train_t.size(0), batch_size):
                idx = permutation[i:i+batch_size]
                batch_x, batch_y = X_train_t[idx], y_train_t[idx]

                optimizer.zero_grad()
                outputs = model(batch_x)
                loss = criterion(outputs, batch_y)
                loss.backward()
                optimizer.step()

                epoch_loss += loss.item() * batch_x.size(0)
                correct += (outputs.argmax(1) == batch_y).sum().item()

            train_loss = epoch_loss / len(X_train_t)
            train_acc = correct / len(X_train_t)

            # Validation
            model.eval()
            with torch.no_grad():
                outputs = model(X_test_t)
                val_loss = criterion(outputs, y_test_t).item()
                val_acc = (outputs.argmax(1) == y_test_t).float().mean().item()

            history["train_loss"].append(train_loss)
            history["val_loss"].append(val_loss)
            history["train_acc"].append(train_acc)
            history["val_acc"].append(val_acc)

            print(f"Epoch {epoch+1}/{n_epochs} - "
                  f"train_acc: {train_acc:.3f}, val_acc: {val_acc:.3f}, "
                  f"train_loss: {train_loss:.3f}, val_loss: {val_loss:.3f}")

        y_pred = outputs.argmax(1).cpu().numpy()

    else:
        # Logistic Regression (scikit-learn)
        model.fit(X_train, y_train)
        y_train_pred = model.predict(X_train)
        y_test_pred = model.predict(X_test)

        train_acc = (y_train_pred == y_train).mean()
        val_acc = (y_test_pred == y_test).mean()
        train_loss = log_loss(y_train, model.predict_proba(X_train))
        val_loss = log_loss(y_test, model.predict_proba(X_test))

        # store one "epoch"
        history["train_acc"].append(train_acc)
        history["val_acc"].append(val_acc)
        history["train_loss"].append(train_loss)
        history["val_loss"].append(val_loss)

        y_pred = y_test_pred

        print(f"Final - train_acc: {train_acc:.3f}, val_acc: {val_acc:.3f}, "
              f"train_loss: {train_loss:.3f}, val_loss: {val_loss:.3f}")

    histories[name] = history

    # Evaluation
    print(f"\n{name} Classification Report (video+audio, chunk-level):\n")
    print(classification_report(y_test, y_pred))

    fig, ax = plt.subplots(figsize=(5, 5))
    ConfusionMatrixDisplay.from_predictions(y_test, y_pred, ax=ax)
    ax.set_title(name + " (video+audio, chunk-level)")
    plt.show()

    # Plot graphs
    plt.figure(figsize=(10, 4))
    plt.subplot(1, 2, 1)
    plt.plot(history["train_acc"], label="train_acc")
    plt.plot(history["val_acc"], label="val_acc")
    plt.title(name + " Accuracy")
    plt.xlabel("Epoch")
    plt.ylabel("Accuracy")
    plt.legend()

    plt.subplot(1, 2, 2)
    plt.plot(history["train_loss"], label="train_loss")
    plt.plot(history["val_loss"], label="val_loss")
    plt.title(name + " Loss")
    plt.xlabel("Epoch")
    plt.ylabel("Log Loss")
    plt.legend()

    plt.suptitle(name + " Training History")
    plt.show()

import torch
import torch.nn as nn
import torch.optim as optim
from sklearn.metrics import log_loss, classification_report, ConfusionMatrixDisplay
import numpy as np
import matplotlib.pyplot as plt

class MultimodalNet(nn.Module):
    def __init__(self, input_dim, hidden_dims=[128, 64, 32], dropout=0.6):
        super().__init__()
        layers = []
        prev_dim = input_dim
        for h in hidden_dims:
            layers.append(nn.Linear(prev_dim, h))
            layers.append(nn.ReLU())
            layers.append(nn.Dropout(dropout))
            prev_dim = h
        layers.append(nn.Linear(prev_dim, 2))
        self.net = nn.Sequential(*layers)

    def forward(self, x):
        return self.net(x)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
X_train_t = torch.tensor(X_train, dtype=torch.float32).to(device)
y_train_t = torch.tensor(y_train, dtype=torch.long).to(device)
X_test_t  = torch.tensor(X_test, dtype=torch.float32).to(device)
y_test_t  = torch.tensor(y_test, dtype=torch.long).to(device)

models = {
    "DNN": MultimodalNet(input_dim=X_train.shape[1]).to(device)
}
n_epochs = 20
batch_size = 32
histories = {}

for name, model in models.items():
    print(f"\nTraining {name} ...")
    history = {"train_loss": [], "val_loss": [], "train_acc": [], "val_acc": []}

    criterion = nn.CrossEntropyLoss()
    optimizer = optim.Adam(model.parameters(), lr=1e-3, weight_decay=1e-4)  # weight_decay = L2

    for epoch in range(n_epochs):
        # ---- Training ----
        model.train()
        permutation = torch.randperm(X_train_t.size(0))
        epoch_loss, correct = 0, 0

        for i in range(0, X_train_t.size(0), batch_size):
            idx = permutation[i:i+batch_size]
            batch_x, batch_y = X_train_t[idx], y_train_t[idx]

            optimizer.zero_grad()
            outputs = model(batch_x)
            loss = criterion(outputs, batch_y)
            loss.backward()
            optimizer.step()

            epoch_loss += loss.item() * batch_x.size(0)
            correct += (outputs.argmax(1) == batch_y).sum().item()

        train_loss = epoch_loss / len(X_train_t)
        train_acc = correct / len(X_train_t)

        # ---- Validation ----
        model.eval()
        with torch.no_grad():
            outputs = model(X_test_t)
            val_loss = criterion(outputs, y_test_t).item()
            val_acc = (outputs.argmax(1) == y_test_t).float().mean().item()

        history["train_loss"].append(train_loss)
        history["val_loss"].append(val_loss)
        history["train_acc"].append(train_acc)
        history["val_acc"].append(val_acc)

        print(f"Epoch {epoch+1}/{n_epochs} - "
              f"train_acc: {train_acc:.3f}, val_acc: {val_acc:.3f}, "
              f"train_loss: {train_loss:.3f}, val_loss: {val_loss:.3f}")

    histories[name] = history


    # ---- Evaluation ----
    y_pred = outputs.argmax(1).cpu().numpy()
    print(f"\n{name} Classification Report (video+audio, chunk-level):\n")
    print(classification_report(y_test, y_pred))

    fig, ax = plt.subplots(figsize=(5, 5))
    ConfusionMatrixDisplay.from_predictions(y_test, y_pred, ax=ax)
    ax.set_title(name + " (video+audio, chunk-level)")
    plt.show()

    # ---- Training curves ----
    plt.figure(figsize=(10, 4))
    plt.subplot(1, 2, 1)
    plt.plot(history["train_acc"], label="train_acc")
    plt.plot(history["val_acc"], label="val_acc")
    plt.title(name + " Accuracy")
    plt.xlabel("Epoch")
    plt.ylabel("Accuracy")
    plt.legend()

    plt.subplot(1, 2, 2)
    plt.plot(history["train_loss"], label="train_loss")
    plt.plot(history["val_loss"], label="val_loss")
    plt.title(name + " Loss")
    plt.xlabel("Epoch")
    plt.ylabel("Log Loss")
    plt.legend()

    plt.suptitle(name + " Training History")
    plt.show()

"""## Final model below"""

import torch
import torch.nn as nn
import torch.optim as optim
from sklearn.metrics import classification_report, ConfusionMatrixDisplay, log_loss
from sklearn.linear_model import LogisticRegression
import numpy as np
import matplotlib.pyplot as plt

# DNN
class MultimodalNet(nn.Module):
    def __init__(self, input_dim, dropout=0.3):
        super().__init__()

        # Funnel-shaped architecture: widen → narrow
        hidden_dims = [
            input_dim // 2,
            input_dim,
            input_dim * 2,
            input_dim,
            max(64, input_dim // 2)
        ]

        layers = []
        prev_dim = input_dim
        for h in hidden_dims:
            layers.append(nn.Linear(prev_dim, h))
            layers.append(nn.ReLU())
            layers.append(nn.Dropout(dropout))
            prev_dim = h

        # Output layer
        layers.append(nn.Linear(prev_dim, 2))
        self.net = nn.Sequential(*layers)

        # Print a summary of the architecture
        print("\n--- MultimodalNet Architecture ---")
        print(f"Input features: {input_dim}")
        for i, h in enumerate(hidden_dims, start=1):
            print(f"  Hidden Layer {i}: Linear({prev_dim}→{h}), ReLU, Dropout(p={dropout})")
            prev_dim = h
        print(f"  Output Layer: Linear({prev_dim}→2)")
        print("-----------------------------------\n")

    def forward(self, x):
        return self.net(x)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
X_train_t = torch.tensor(X_train, dtype=torch.float32).to(device)
y_train_t = torch.tensor(y_train, dtype=torch.long).to(device)
X_test_t  = torch.tensor(X_test, dtype=torch.float32).to(device)
y_test_t  = torch.tensor(y_test, dtype=torch.long).to(device)

# Models list
models = {
    "DNN": MultimodalNet(input_dim=X_train.shape[1]).to(device),
}

n_epochs = 20
batch_size = 64
histories = {}

for name, model in models.items():
    print(f"\nTraining {name} ...")
    history = {"train_loss": [], "val_loss": [], "train_acc": [], "val_acc": []}

    if name == "DNN":
        # PyTorch training loop
        criterion = nn.CrossEntropyLoss()
        optimizer = optim.Adam(model.parameters(), lr=1e-3, weight_decay=1e-4)

        for epoch in range(n_epochs):

            model.train()
            permutation = torch.randperm(X_train_t.size(0))
            epoch_loss, correct = 0, 0

            for i in range(0, X_train_t.size(0), batch_size):
                idx = permutation[i:i+batch_size]
                batch_x, batch_y = X_train_t[idx], y_train_t[idx]

                optimizer.zero_grad()
                outputs = model(batch_x)
                loss = criterion(outputs, batch_y)
                loss.backward()
                optimizer.step()

                epoch_loss += loss.item() * batch_x.size(0)
                correct += (outputs.argmax(1) == batch_y).sum().item()

            train_loss = epoch_loss / len(X_train_t)
            train_acc = correct / len(X_train_t)

            # Validation
            model.eval()
            with torch.no_grad():
                outputs = model(X_test_t)
                val_loss = criterion(outputs, y_test_t).item()
                val_acc = (outputs.argmax(1) == y_test_t).float().mean().item()

            history["train_loss"].append(train_loss)
            history["val_loss"].append(val_loss)
            history["train_acc"].append(train_acc)
            history["val_acc"].append(val_acc)

            print(f"Epoch {epoch+1}/{n_epochs} - "
                  f"train_acc: {train_acc:.3f}, val_acc: {val_acc:.3f}, "
                  f"train_loss: {train_loss:.3f}, val_loss: {val_loss:.3f}")

        y_pred = outputs.argmax(1).cpu().numpy()

    else:
        # Logistic Regression (scikit-learn)
        model.fit(X_train, y_train)
        y_train_pred = model.predict(X_train)
        y_test_pred = model.predict(X_test)

        train_acc = (y_train_pred == y_train).mean()
        val_acc = (y_test_pred == y_test).mean()
        train_loss = log_loss(y_train, model.predict_proba(X_train))
        val_loss = log_loss(y_test, model.predict_proba(X_test))

        # store one "epoch"
        history["train_acc"].append(train_acc)
        history["val_acc"].append(val_acc)
        history["train_loss"].append(train_loss)
        history["val_loss"].append(val_loss)

        y_pred = y_test_pred

        print(f"Final - train_acc: {train_acc:.3f}, val_acc: {val_acc:.3f}, "
              f"train_loss: {train_loss:.3f}, val_loss: {val_loss:.3f}")

    histories[name] = history

    # Evaluation
    print(f"\n{name} Classification Report (video+audio, chunk-level):\n")
    print(classification_report(y_test, y_pred))

    fig, ax = plt.subplots(figsize=(5, 5))
    ConfusionMatrixDisplay.from_predictions(y_test, y_pred, ax=ax)
    ax.set_title(name + " (video+audio, chunk-level)")
    plt.show()

    # Plot graphs
    plt.figure(figsize=(10, 4))
    plt.subplot(1, 2, 1)
    plt.plot(history["train_acc"], label="train_acc")
    plt.plot(history["val_acc"], label="val_acc")
    plt.title(name + " Accuracy")
    plt.xlabel("Epoch")
    plt.ylabel("Accuracy")
    plt.legend()

    plt.subplot(1, 2, 2)
    plt.plot(history["train_loss"], label="train_loss")
    plt.plot(history["val_loss"], label="val_loss")
    plt.title(name + " Loss")
    plt.xlabel("Epoch")
    plt.ylabel("Log Loss")
    plt.legend()

    plt.suptitle(name + " Training History")
    plt.show()









"""## **(Pred1 + Pred2) / 2 >= 0.5**"""

import re
import numpy as np
import pandas as pd
import pickle
from pathlib import Path
from collections import defaultdict


mfcc_csv = "/content/drive/MyDrive/Project Data/audio/audio_chunks/chunks_metadata_with_mfcc.csv"
frame_feat_path = "/content/drive/MyDrive/Project Data/cv_features/fc1_fc2_features_frame.pkl"

mfcc_df = pd.read_csv(mfcc_csv)

mfcc_df = mfcc_df[mfcc_df["subfolder_audio"].isin(["passage_1","passage_2","passage_3"])]

mfcc_cols = [c for c in mfcc_df.columns if c.lower().startswith("mfcc")]

with open(frame_feat_path, "rb") as f:
    frame_feats = pickle.load(f)

def label_to_group(label_str):
    if pd.isna(label_str):
        return None
    s = str(label_str).lower()
    if "control" in s or "negative" in s:
        return "control"
    if "positive" in s or "experimental" in s:
        return "experimental"
    return "control" if "control" in s else "experimental"

def subject_key_candidates(pid):
    # raw
    if pd.isna(pid):
        return []
    pid = str(pid).strip()
    cands = []
    cands.append(pid)
    cands.append(pid.replace("-", "_"))
    cands.append(pid.replace("-", "."))
    cands.append(pid.replace("_", "."))
    cands.append(pid.replace(".", "_"))
    no_paren = re.sub(r"\(.*?\)", "", pid).strip()
    cands.append(no_paren)
    cands.append(no_paren.replace("-", "_"))
    cands.append(no_paren.replace(".", "_"))
    def collapse(s):
        s = re.sub(r'[_\.\-]{2,}', '_', s)
        s = s.strip("_.- ")
        return s
    cands = [collapse(x) for x in cands if x]
    seen = set()
    out = []
    for x in cands:
        if x not in seen:
            seen.add(x)
            out.append(x)
    return out

def find_subject_in_group(group_dict, pid):
    for cand in subject_key_candidates(pid):
        if cand in group_dict:
            return cand
    return None

aligned_audio = []
aligned_video = []
aligned_labels = []
aligned_subjects = []
aligned_passages = []

missing_subjects = set()
missing_passages = []
zero_clips = 0
skipped = 0

CHUNK_LEN = 15

# iterate rows
for idx, row in mfcc_df.iterrows():
    pid = row.get("participant_id")
    passage = row.get("subfolder_audio")
    seg_idx = row.get("segment_index")
    duration = row.get("duration")
    label_raw = row.get("label")
    group = label_to_group(label_raw)

    if group not in frame_feats:

        missing_subjects.add((pid, group))
        skipped += 1
        continue

    subj_key = find_subject_in_group(frame_feats[group], pid)
    if subj_key is None:
        missing_subjects.add(pid)
        skipped += 1
        continue

    passages = frame_feats[group][subj_key]
    if passage not in passages:
        missing_passages.append((subj_key, passage))
        skipped += 1
        continue

    video_arr = passages[passage]
    if video_arr is None or video_arr.shape[0] == 0:
        zero_clips += 1
        continue

    try:
        seg_idx_i = int(seg_idx) - 1
    except Exception:
        seg_idx_i = None

    num_frames = video_arr.shape[0]

    if seg_idx_i is not None and seg_idx_i >= 0:
        start_frame = seg_idx_i * CHUNK_LEN
        if pd.notna(duration) and duration > 0:
            end_frame = start_frame + int(np.ceil(float(duration)))
        else:
            end_frame = start_frame + CHUNK_LEN
    else:
        start_time = row.get("start_time", 0.0)
        end_time = row.get("end_time", start_time + CHUNK_LEN)
        start_frame = int(np.floor(float(start_time)))
        end_frame = int(np.ceil(float(end_time)))

    if start_frame < 0:
        start_frame = 0
    if end_frame > num_frames:
        end_frame = num_frames

    if start_frame >= end_frame:
        zero_clips += 1
        continue

    video_chunk = video_arr[start_frame:end_frame]
    if video_chunk.shape[0] == 0:
        zero_clips += 1
        continue


    video_feat = video_chunk.mean(axis=0)

    audio_vec = row[mfcc_cols].values.astype(float)

    aligned_audio.append(audio_vec)
    aligned_video.append(video_feat)
    aligned_labels.append(0 if "control" in str(label_raw).lower() or "negative" in str(label_raw).lower() else 1)
    aligned_subjects.append(subj_key)
    aligned_passages.append(passage)

aligned_audio = np.array(aligned_audio)
aligned_video = np.array(aligned_video)
aligned_labels = np.array(aligned_labels)
aligned_subjects = np.array(aligned_subjects)
aligned_passages = np.array(aligned_passages)

# diagnostics
print("Audio chunks:", aligned_audio.shape)
print("Video chunks:", aligned_video.shape)
print("Labels:", aligned_labels.shape)
print("Unique subjects:", len(np.unique(aligned_subjects)))
print("Example subject:", aligned_subjects[0], "Passage:", aligned_passages[0])
print("MFCC example shape:", aligned_audio[0].shape if aligned_audio.size else None)
print("Video example shape:", aligned_video[0].shape if aligned_video.size else None)

print("\nSkipped rows:", skipped)
print("Zero-length video chunks:", zero_clips)
print("Missing subject examples (up to 10):", list(missing_subjects)[:10])
print("Missing passage examples (up to 10):", missing_passages[:10])

import numpy as np
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import classification_report, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression


X_audio = aligned_audio
X_video = aligned_video
y = aligned_labels
subjects = aligned_subjects


skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

audio_clf = LogisticRegression(max_iter=500)
video_clf = RandomForestClassifier(n_estimators=200, random_state=42)

all_y_true = []
all_y_pred_fused = []

for fold, (train_idx, test_idx) in enumerate(skf.split(X_audio, y)):
    X_audio_train, X_audio_test = X_audio[train_idx], X_audio[test_idx]
    X_video_train, X_video_test = X_video[train_idxA], X_video[test_idx]
    y_train, y_test = y[train_idx], y[test_idx]

    audio_clf.fit(X_audio_train, y_train)
    audio_probs = audio_clf.predict_proba(X_audio_test)[:, 1]

    video_clf.fit(X_video_train, y_train)
    video_probs = video_clf.predict_proba(X_video_test)[:, 1]

    fused_probs = (audio_probs + video_probs) / 2
    fused_pred = (fused_probs >= 0.5).astype(int)

    all_y_true.extend(y_test)
    all_y_pred_fused.extend(fused_pred)

    print(f"Fold {fold+1} classification report:")
    print(classification_report(y_test, fused_pred))

print("\nFinal combined decision report:")
print(classification_report(all_y_true, all_y_pred_fused))

ConfusionMatrixDisplay.from_predictions(all_y_true, all_y_pred_fused)
plt.show()

import numpy as np
from sklearn.model_selection import GroupKFold
from sklearn.metrics import classification_report, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression

X_audio = aligned_audio
X_video = aligned_video
y = aligned_labels
subjects = aligned_subjects

gkf = GroupKFold(n_splits=5)

audio_clf = LogisticRegression(max_iter=500)
video_clf = RandomForestClassifier(n_estimators=200, random_state=42)

all_y_true = []
all_y_pred_fused = []

for fold, (train_idx, test_idx) in enumerate(gkf.split(X_audio, y, groups=subjects)):
    X_audio_train, X_audio_test = X_audio[train_idx], X_audio[test_idx]
    X_video_train, X_video_test = X_video[train_idx], X_video[test_idx]
    y_train, y_test = y[train_idx], y[test_idx]

    audio_clf.fit(X_audio_train, y_train)
    audio_probs = audio_clf.predict_proba(X_audio_test)[:, 1]

    video_clf.fit(X_video_train, y_train)
    video_probs = video_clf.predict_proba(X_video_test)[:, 1]

    fused_probs = (audio_probs + video_probs) / 2
    fused_pred = (fused_probs >= 0.5).astype(int)

    all_y_true.extend(y_test)
    all_y_pred_fused.extend(fused_pred)

    print(f"Fold {fold+1} classification report:")
    print(classification_report(y_test, fused_pred))

print("\nFinal combined decision report:")
print(classification_report(all_y_true, all_y_pred_fused))

ConfusionMatrixDisplay.from_predictions(all_y_true, all_y_pred_fused)
plt.show()

import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import GroupKFold
from sklearn.metrics import classification_report, ConfusionMatrixDisplay

from sklearn.ensemble import GradientBoostingClassifier, RandomForestClassifier
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier
from sklearn.linear_model import LogisticRegression


X_audio = aligned_audio
X_video = aligned_video
y = aligned_labels
subjects = aligned_subjects

gkf = GroupKFold(n_splits=5)

audio_clf = GradientBoostingClassifier(n_estimators=300, learning_rate=0.05, random_state=42)

video_clf = GradientBoostingClassifier(n_estimators=300, learning_rate=0.05, random_state=42)


all_y_true = []
all_y_pred_fused = []

for fold, (train_idx, test_idx) in enumerate(gkf.split(X_audio, y, groups=subjects)):
    print(f"\n===== Fold {fold+1} =====")
    X_audio_train, X_audio_test = X_audio[train_idx], X_audio[test_idx]
    X_video_train, X_video_test = X_video[train_idx], X_video[test_idx]
    y_train, y_test = y[train_idx], y[test_idx]

    audio_clf.fit(X_audio_train, y_train)
    audio_probs = audio_clf.predict_proba(X_audio_test)[:, 1]

    video_clf.fit(X_video_train, y_train)
    video_probs = video_clf.predict_proba(X_video_test)[:, 1]

    fused_probs = (audio_probs + video_probs) / 2
    fused_pred = (fused_probs >= 0.5).astype(int)

    all_y_true.extend(y_test)
    all_y_pred_fused.extend(fused_pred)

    print(classification_report(y_test, fused_pred, digits=3))

print("\n=== Final combined decision report ===")
print(classification_report(all_y_true, all_y_pred_fused, digits=3))

ConfusionMatrixDisplay.from_predictions(all_y_true, all_y_pred_fused)
plt.show()

# audio_clf = SVC(probability=True, kernel='rbf', C=2, gamma='scale', random_state=42)
audio_clf = MLPClassifier(hidden_layer_sizes=(128,64), activation='relu', solver='adam', max_iter=500, random_state=42)

# video_clf = SVC(probability=True, kernel='rbf', C=2, gamma='scale', random_state=42)
video_clf = MLPClassifier(hidden_layer_sizes=(256,128), activation='relu', solver='adam', max_iter=500, random_state=42)

all_y_true = []
all_y_pred_fused = []

for fold, (train_idx, test_idx) in enumerate(gkf.split(X_audio, y, groups=subjects)):
    print(f"\n===== Fold {fold+1} =====")
    X_audio_train, X_audio_test = X_audio[train_idx], X_audio[test_idx]
    X_video_train, X_video_test = X_video[train_idx], X_video[test_idx]
    y_train, y_test = y[train_idx], y[test_idx]

    audio_clf.fit(X_audio_train, y_train)
    audio_probs = audio_clf.predict_proba(X_audio_test)[:, 1]

    video_clf.fit(X_video_train, y_train)
    video_probs = video_clf.predict_proba(X_video_test)[:, 1]

    fused_probs = (audio_probs + video_probs) / 2
    fused_pred = (fused_probs >= 0.5).astype(int)

    all_y_true.extend(y_test)
    all_y_pred_fused.extend(fused_pred)

    print(classification_report(y_test, fused_pred, digits=3))

print("\n=== Final combined decision report ===")
print(classification_report(all_y_true, all_y_pred_fused, digits=3))

ConfusionMatrixDisplay.from_predictions(all_y_true, all_y_pred_fused)
plt.show()





