# -*- coding: utf-8 -*-
"""CV_Chunks

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O0AozTOVHBXEy6OqVSPf9B41m98NuHtz
"""

import os
import re
import pandas as pd
from moviepy.editor import VideoFileClip
from moviepy.video.io.ffmpeg_tools import ffmpeg_extract_subclip
import glob
from pathlib import Path
import shutil

try:
    from google.colab import drive
    drive.mount('/content/drive')
except Exception:
    pass

pd.set_option('display.max_rows', None)

NEG_VID = Path("/content/drive/MyDrive/Project Data/Negative_class/Клинические данные - контрольная группа")
# NEG_VID = Path("/content/drive/MyDrive/Project Data/Negative_class/focus")
# POS_VID = Path("/content/drive/MyDrive/Project Data/Positive_class/video")
# POS_VID = Path("/content/drive/MyDrive/Project Data/Positive_class/restart")

NEG_CSV = Path("/content/drive/MyDrive/Project Data/Negative_class/datasets/Клинические")
POS_CSV = Path("/content/drive/MyDrive/Project Data/Positive_class/datasets")

OUTPUT_DIR = Path("/content/drive/MyDrive/Project Data/video_chunks")
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

def match_sequence(words, seq, start_idx):
    """
    Checks if seq matches words starting from start_idx.
    seq may contain strings or lists of alternative strings.
    """
    if start_idx + len(seq) > len(words):
        return False
    for i, token in enumerate(seq):
        word = words[start_idx + i]
        if isinstance(token, list):
            if word not in token:
                return False
        else:
            if word != token:
                return False
    return True

def match_word(word, target):
    """
    Returns True if the word matches the target.
    target can be a string or a list of alternative strings.
    Case-insensitive.
    """
    word = str(word).strip().lower()

    if isinstance(target, list):
        return word in [str(t).strip().lower() for t in target]
    else:
        return word == str(target).strip().lower()


def find_phrase(df, phrase_seq, return_end=False):
    """
    Finds the first time phrase_seq appears in the dataframe words column.
    If return_end=False → returns start_time of the first word in the match.
    If return_end=True  → returns end_time of the last word in the match.
    Returns None if no match is found.
    """
    words = df["text"].tolist()
    seq_len = len(phrase_seq)
    for idx in range(len(words) - seq_len + 1):
        if match_sequence(words, phrase_seq, idx):
            print(phrase_seq)
            if return_end:
                print(df.iloc[idx + seq_len - 1]['text'])
                return df.iloc[idx + seq_len - 1]["end_time"]
            else:
                print(df.iloc[idx]['text'])
                return df.iloc[idx]["start_time"]
    return None


def find_passage_timestamps(df, alternatives):
    """
    Try all alternatives: each has start_phrase and end_phrase.
    Returns (start_time, end_time) of first matching alternative.
    """
    for alt in alternatives:
        start_time = find_phrase_fuzzy(df, alt["start_phrase"], return_end=False)
        if start_time is None:
            continue
        end_time   = find_phrase_fuzzy(df, alt["end_phrase"], return_end=True)
        if end_time is None:
            continue
        return start_time, end_time
    return None, None

def find_phrase_fuzzy(df, phrase_seq, return_end=False, max_gap=3):
    """
    Finds the first fuzzy match for phrase_seq in df['text'].
    Allows noise words between matches (max_gap controls the allowed distance).

    return_end=False → returns start_time of the first matched word
    return_end=True  → returns end_time of the last matched word
    """
    words = df["text"].tolist()

    for i in range(len(words)):
        w_idx = i
        s_idx = 0
        matched_indices = []

        while s_idx < len(phrase_seq) and w_idx < len(words):
            if match_word(words[w_idx], phrase_seq[s_idx]):
                matched_indices.append(w_idx)
                s_idx += 1
            w_idx += 1

            # too big a gap since last matched word → stop
            if matched_indices and w_idx - matched_indices[-1] > max_gap + 1:
                break

        if s_idx == len(phrase_seq):  # found a complete sequence
            if return_end:
                return df.iloc[matched_indices[-1]]["end_time"]
            else:
                return df.iloc[matched_indices[0]]["start_time"]

    return None

def clean_text(text):
    """Lowercase and remove punctuation from text."""
    text = str(text).lower()
    text = re.sub(r'[.,!?;:“”"\'—–\-«»]', '', text)
    return text.strip()

# def find_index_fuzzy(words, seq, use_end=False, max_gap=3):
#     for i in range(len(words)):
#         w_idx = i
#         s_idx = 0
#         matched_indices = []

#         while s_idx < len(seq) and w_idx < len(words):
#             if words[w_idx] == seq[s_idx]:
#                 matched_indices.append(w_idx)
#                 s_idx += 1
#             w_idx += 1
#             if matched_indices and w_idx - matched_indices[-1] > max_gap + 1:
#                 break

#         if s_idx == len(seq):
#             return matched_indices[-1] if use_end else matched_indices[0]
#     return None

# def find_passage_timestamps(df, start_seq, end_seq):
#     words = df["text"].tolist()
#     start_idx = find_index_fuzzy(words, start_seq, use_end=False)
#     end_idx = find_index_fuzzy(words, end_seq, use_end=True)

#     if start_idx is not None and end_idx is not None and end_idx >= start_idx:
#         return float(df.iloc[start_idx]["start_time"]), float(df.iloc[end_idx]["end_time"])
#     return None, None

def process_group(video_dir: Path, csv_dir: Path, group_name: str):
    for csv_file in csv_dir.glob("*.csv"):
        # Extract subject base name without "_transcript"
        subject_base = csv_file.stem.replace("_transcript", "")

        # Try to find matching video
        video_file = next(video_dir.glob(f"{subject_base}.mp4"), None)
        if not video_file:
            print(f"⚠ No video found for {subject_base} in {group_name}")
            continue

        # Load and clean transcription
        df = pd.read_csv(csv_file)
        if not {"text", "start_time", "end_time"}.issubset(df.columns):
            print(f"⚠ Invalid CSV format: {csv_file}")
            continue

        df["text"] = df["text"].astype(str).apply(clean_text)

        # Load video
        video = VideoFileClip(str(video_file))
        print(f"🎬 Processing {subject_base} ({group_name})")

        # Output subject dir
        subject_out_dir = OUTPUT_DIR / group_name / subject_base
        subject_out_dir.mkdir(parents=True, exist_ok=True)

        # Extract passages
        for passage in passages:
            # start_time, end_time = find_passage_timestamps(df, passage["start_phrase"], passage["end_phrase"])
            start_time, end_time = find_passage_timestamps(df, passage["alternatives"])
            if start_time is None or end_time is None:
                print(f"  ⏩ Skipping {passage['name']} (not found)")
                continue

            if end_time > video.duration:
                print(f"  ⚠ End time exceeds duration for {passage['name']} → clamped")
                end_time = video.duration

            print(f"  ✂ Trimming {passage['name']}: {start_time:.2f} - {end_time:.2f}")
            try:
                trimmed = video.subclip(start_time, end_time)
                passage_dir = subject_out_dir / passage["name"]
                passage_dir.mkdir(parents=True, exist_ok=True)

                s_fmt = f"{start_time:.2f}".replace('.', '_')
                e_fmt = f"{end_time:.2f}".replace('.', '_')

                output_filename = f"{passage['name']}_{s_fmt}_{e_fmt}.mp4"
                final_path = passage_dir / output_filename

                # write first to local tmp to avoid drive I/O issues
                temp_path = Path("/tmp") / output_filename

                try:
                    trimmed.write_videofile(
                        str(temp_path),
                        codec="libx264",
                        audio_codec="aac",
                        fps=video.fps,
                        ffmpeg_params=["-movflags", "+faststart"],
                        verbose=False,
                        logger=None
                    )
                    shutil.move(str(temp_path), str(final_path))
                    print(f"  ✅ Saved {final_path}")

                except Exception as e:
                    print(f"  ❌ Failed to trim {passage['name']}: {e}")

                finally:
                    if temp_path.exists():
                        try:
                            temp_path.unlink()
                        except Exception:
                            pass

            except Exception as e:
                print(f"  ❌ Failed processing passage {passage['name']}: {e}")

        video.close()

process_group(NEG_VID, NEG_CSV, "control")

passages = [
    {
        "name": "passage_1",
        "alternatives": [
            {
                "start_phrase": ['система', 'мира', ['ксения', 'ксении']],
                "end_phrase": [["мира", "мир"], ["такова", 'такая', "отакова", "таков", 'такого'], ["система", "тема", 'системы']]
            },
            {
                "start_phrase": ['система', 'мира', ['ксения', 'ксении']],
                "end_phrase": ['одиночестве', ['умрешь', 'умрёшь'], ['таковой', 'такого'], 'системы']
            },
            {
                "start_phrase": [['меня', 'мне'], 'пугает', 'этот', 'мир'],
                "end_phrase": ['одиночестве', ['умрешь', 'умрёшь'], ['таковой', 'такого', 'умирает'], ['системы', 'системе']]
            },
            {
                "start_phrase": [['меня', 'мне'], 'пугает', 'этот', 'мир'],
                "end_phrase": [["мира", "мир"], ["такова", "таков", "какова"], ["система", "тема"]]
            },
             {
                "start_phrase": [['меня', 'мне'], 'пугает', 'этот', 'мир'],
                "end_phrase": [["такова"], ["мира"], ["система", "тема"]]
            },
            {
                "start_phrase": ['система', 'мира', ['ксения', 'ксении']],
                "end_phrase": ['в', 'одиночестве', ['умрешь', 'умрёшь']]
            },
        ]
    },
    {
        "name": "passage_2",
        "alternatives": [
            {
                "start_phrase": ['я', 'люблю', ['тебя', 'тебе'], ['жизни', 'жизнь'], ['что', 'и'], ['само', 'сама', 'самого'], ['по', 'бы', 'посея'], ['себе', 'ненаво']],
                "end_phrase": [['надеюсь', 'додеюсь', 'надей'], 'что', ['это', 'этого'], ['взаимно', 'взвоимно', 'имя', 'займёт', 'ино', 'имна', 'имена']],
            },
            {
                "start_phrase": ['я', 'люблю', ['тебя', 'тебе'], ['жизни', 'жизнь'], 'что', ['само', 'сама', 'самого'], ['по', 'бы', 'посея'], ['себе', 'ненаво']],
                "end_phrase": [['надеюсь', 'додеюсь', 'надей'], ['это', 'этого'], ['взаимно', 'взвоимно', 'имя', 'займёт', 'ино', 'имна', 'имена']],
            },
            # {
            #     "start_phrase": [],
            #     "end_phrase": []
            # }
        ]
    },
    {
        "name": "passage_3",
        "alternatives": [
            {
                "start_phrase": ['мир', 'вокруг', ['стал', 'столкнулся'], ['тусклым', 'тусклый', 'тосклым', 'пустым', 'тускливым', 'туском'], 'как', ['забытая', 'забутая'], 'картина'],
                "end_phrase": ['кажется', 'что', ['так', 'это'], 'будет', ['всегда', 'так']],
            },
            {
                "start_phrase": ['вокруг', ['стал', 'столкнулся'], ['тусклым', 'тусклый', 'тосклым', 'пустым', 'тускливым', 'туском'], 'как', ['забытая', 'забутая'], 'картина'],
                "end_phrase": ['кажется', 'что', ['так', 'это'], 'будет', ['всегда', 'так']],
            },
            {
                "start_phrase": ['мир', 'вокруг', ['стал', 'столкнулся'], ['тусклым', 'тусклый', 'тосклым', 'пустым', 'тускливым', 'туском'], 'как', ['забытая', 'забутая'], 'картина'],
                "end_phrase": ['кажется', ['так', 'это'], 'будет', ['всегда', 'так']],
            },
            {
                "start_phrase": ['мир','вокруг', ['стал', 'столкнулся'], ['тусклым', 'тусклый', 'тосклым', 'пустым', 'тускливым', 'туском']],
                "end_phrase": ['внутри', 'и','так', 'будет', 'всегда'],
            },
            {
                "start_phrase": ['как', 'забытая', 'картина'],
                "end_phrase": ['внутри', 'и','так', 'будет', 'всегда'],
            },
            {
                "start_phrase": ['которой', 'когда', 'были', "яркие"],
                "end_phrase": ['кажется', 'что', ['так', 'это'], 'будет', ['всегда', 'так']],
            },
            # {
            #     "start_phrase": [],
            #     "end_phrase": []
            # }
        ]
    }
]

output_dir = OUTPUT_DIR

def match_word(word, target):
    word = str(word).strip().lower()
    if isinstance(target, list):
        return word in [str(t).strip().lower() for t in target]
    else:
        return word == str(target).strip().lower()

def find_index_fuzzy(words, seq, use_end=False, max_gap=3):
    for i in range(len(words)):
        w_idx = i
        s_idx = 0
        matched = []
        while s_idx < len(seq) and w_idx < len(words):
            if match_word(words[w_idx], seq[s_idx]):
                matched.append(w_idx)
                s_idx += 1
            w_idx += 1
            if matched and w_idx - matched[-1] > max_gap + 1:
                break
        if s_idx == len(seq):
            return matched[-1] if use_end else matched[0]
    return None

def normalize_subject_id(name_or_path):
    base = os.path.splitext(os.path.basename(str(name_or_path)))[0]
    if base.endswith("_transcript"):
        base = base[: -len("_transcript")]
    return base

def build_annotation_map(dirs_by_group):
    ann_map = {}
    for _, folder in dirs_by_group.items():
        if not Path(folder).exists():
            continue
        for f in os.listdir(folder):
            if f.lower().endswith(".csv"):
                sid = normalize_subject_id(f)
                ann_map[sid] = os.path.join(folder, f)
    return ann_map

def build_video_and_group_maps(dirs_by_group):
    vid_map, group_map = {}, {}
    for group_name, folder in dirs_by_group.items():
        if not Path(folder).exists():
            continue
        for f in os.listdir(folder):
            if f.lower().endswith((".mp4", ".mov", ".avi", ".mkv")):
                sid = normalize_subject_id(f)
                vid_map[sid] = os.path.join(folder, f)
                group_map[sid] = group_name  # "control" or "experimental"
    return vid_map, group_map

csv_dirs = {"control": str(NEG_CSV), "experimental": str(POS_CSV)}
video_dirs = {"control": str(NEG_VID), "experimental": str(POS_VID)}

annotation_map = build_annotation_map(csv_dirs)
video_map, group_map = build_video_and_group_maps(video_dirs)


for subject_id in annotation_map:
    if subject_id not in video_map:
        print(f"No video for {subject_id}")
        continue

    print(f"Processing {subject_id}")
    group = group_map.get(subject_id, "unknown")

    video = VideoFileClip(video_map[subject_id])

    df = pd.read_csv(annotation_map[subject_id])
    # df["text"] = df["text"].astype(str).str.lower()
    df["text"] = df["text"].astype(str).apply(clean_text)
    words = df["text"].tolist()

    question_times = []

    for q in question_phrases:
        qnum = q["question_num"]
        found = False
        for alt in q["alternatives"]:

            start_idx = find_index_fuzzy(words, alt["start_phrase"], use_end=False)
            end_idx = find_index_fuzzy(words, alt["end_phrase"], use_end=True)

            if start_idx is not None and end_idx is not None and end_idx >= start_idx:
                start_time = float(df.iloc[start_idx]["start_time"])
                end_time = float(df.iloc[end_idx]["end_time"])
                question_times.append((qnum, start_time, end_time))
                found = True
                break

        if not found:
            print(f"Could not find full question {q['question_num']} for {subject_id}")

    if len(question_times) < 2:
        print(f"Not enough questions found for {subject_id}")
        video.close()
        continue

    # Output base dir for this subject's questions
    subject_out_dir = os.path.join(output_dir, group, subject_id)
    os.makedirs(subject_out_dir, exist_ok=True)

    # Create clips for each question's answer
    for i in range(len(question_times) - 1):
        qnum, q_start, q_end = question_times[i]
        answer_start = q_end
        answer_end = question_times[i + 1][1]

        if answer_start >= answer_end or answer_end > video.duration:
            continue

        segment_dir = os.path.join(subject_out_dir, f"q{qnum:02d}")
        os.makedirs(segment_dir, exist_ok=True)

        start_str = f"{answer_start:.2f}".replace('.', '_')
        end_str = f"{answer_end:.2f}".replace('.', '_')

        segment_name = f"q{qnum:02d}_answer_{start_str}_{end_str}.mp4"
        out_path = os.path.join(segment_dir, segment_name)

        try:
            print(f"✂ Trimming Q{qnum:02d} [{answer_start:.2f}-{answer_end:.2f}] -> {segment_name}")
            clip = video.subclip(answer_start, answer_end)
            clip.write_videofile(
                out_path,
                codec="libx264", audio_codec="aac", fps=video.fps,
                verbose=False, logger=None
            )
            print(f"  ✅ Saved {segment_name}")
        except Exception as e:
            print(f"  ❌ Failed to save {segment_name}: {e}")

    video.close()

question_phrases = [
    {"question_num": 1,
         "alternatives": [
             {"start_phrase": ["как", "вы", "чувствуете"],
              "end_phrase": ["описать", "ощущения"]}]},
    {"question_num": 2,
         "alternatives": [
             {"start_phrase": ["что", "что", "помогает", "вам"],
              "end_phrase": ["что", "что", "ваше", "состояние"]}]},
    {"question_num": 3,
         "alternatives": [
             {"start_phrase": [["замечали", "заметили", "замечаешь"], "что", "настроение", "изменилось"],
              "end_phrase": ["последнее", "время", ["есть", "если"], ["изменилось", "да"], "как"]}]},
    {"question_num": 4,
         "alternatives": [
             {"start_phrase": ["чувствуете", "что", "вас", ["есть", "если"], ["энергия", "энергии"]],
              "end_phrase": [["сила", "силы"], ["справляться", "справиться"], ["повседневными", "повсененными", "повсидиаблами"], "задачами"]}]},
    {"question_num": 5,
         "alternatives": [
             {"start_phrase": ["вы", "часто", "думаете", "что", ["сможете", "можете"]],
              "end_phrase": ["что", "ничего", "имеет", ["смысла", "смысл"]]}]},
    {"question_num": 6,
         "alternatives": [
             {"start_phrase": [["есть", "если"], "вас", "моменты", "когда", "вы", "радость"],
              "end_phrase": ["такие", "моменты", "стали", "реже"]},
             {"start_phrase": ['сейчас', 'такие', 'моменты', 'стали', 'реже', 'хоть',],
              "end_phrase": [['моменты'],["стали"], ["реже"]]},
             {"start_phrase": [["есть", "если"], "вас", "моменты", "когда", "вы", "радость"],
              "end_phrase": ["радость", "и", "удовлетворение", "моменты"]}
         ]},
    {"question_num": 7,
         "alternatives": [
             {"start_phrase": ["как", "вы", "спите", "бывают", "проблемы"],
              "end_phrase": ["как", "влияет", ["ваше", "ваши"], ["самочувствие","самочувствия", "чувствия", "чувства", "чувство"]]},
             {"start_phrase": ["как", "вы", "спите", "бывают", "ли", "проблемы"],
              "end_phrase": ["засыпанием", "с", "просыпанием", "и", "как"]}
         ]},
    {"question_num": 8,
         "alternatives": [
             {"start_phrase": [["чувствуете", "чувствует"], "что", "теряете", "интерес", "вещам"],
              "end_phrase": ["раньше", "приносили", ["удовлетворения", "удастся"]]}]},
    {"question_num": 9,
         "alternatives": [
             {"start_phrase": ["как", ["ваши", "ваше"], ["отношения", "отношение"], ["близкими", "близким"]],
              "end_phrase": ["ощущение", "что", "кто", "поддерживает", "чувствуете", "себя", ["изолированно", "изолированной", "изолированными"]]}]},
    {"question_num": 10,
         "alternatives": [
             {"start_phrase": ["что", "вашему", "мнению", "могло", "помочь"],
              "end_phrase": ["сейчас", "облегчить", "ваше", "состояние"]}]},
    {"question_num": 11,
         "alternatives": [
                {"start_phrase": [["три"], ["ассоциации"], ["на"], ["и"], ["короткий"], ["рассказ"]],
                 "end_phrase": [["короткий"], ["рассказ"]]},
                {"start_phrase": [["ассоциации"], ["и"], ["короткий"], ["рассказ"]],
                 "end_phrase": [["короткий"], ["рассказ"]]},
                {"start_phrase": [["назвать"], ["ассоциации"], ["которые"], ["вам"]],
                 "end_phrase": [["течении"], ["50"], ["секунд"]]}

    ]}
]

test_word = pd.read_csv(NEG_CSV /'015_2025.03.06_transcript.csv')
test_word["text"] = test_word["text"].astype(str).apply(clean_text)
test_word

