# -*- coding: utf-8 -*-
"""FaceDetection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_3ZK9u70OnQpSM-GqaOu_4iNIwq0JwJN
"""

import os
import cv2
from retinaface import RetinaFace
from pathlib import Path

try:
    from google.colab import drive
    drive.mount('/content/drive')
except Exception:
    pass

video_root_folder = Path("/content/drive/MyDrive/Project Data/video_chunks/check")
output_faces_folder = Path("/content/drive/MyDrive/Project Data/Frames")

for group in os.listdir(video_root_folder):
    group_path = os.path.join(video_root_folder, group)
    if not os.path.isdir(group_path):
        continue

    for subject in os.listdir(group_path):
        subject_path = os.path.join(group_path, subject)
        if not os.path.isdir(subject_path):
            continue


        for subfolder in os.listdir(subject_path):
            subfolder_path = os.path.join(subject_path, subfolder)
            if not os.path.isdir(subfolder_path):
                continue

            for video_file in os.listdir(subfolder_path):
                if not video_file.lower().endswith(".mp4"):
                    continue
                # single chunk starts here
                video_path = os.path.join(subfolder_path, video_file)
                cap = cv2.VideoCapture(video_path)

                if not cap.isOpened():
                    print(f"Error opening {video_file}")
                    continue

                print(f"Processing: {video_path}")
                video_name = os.path.splitext(video_file)[0]
                fps = cap.get(cv2.CAP_PROP_FPS) or 25
                interval = max(int(fps / 1), 1)

                frame_idx = 0
                while True:
                    ret, frame = cap.read()
                    if not ret:
                        break

                    if frame_idx % interval == 0:
                        try:
                            faces = RetinaFace.detect_faces(frame)
                            if isinstance(faces, dict):
                                for i, key in enumerate(faces.keys()):
                                    face = faces[key]['facial_area']
                                    x1, y1, x2, y2 = map(int, face)
                                    cropped_face = frame[y1:y2, x1:x2]

                                    output_path = os.path.join(
                                        output_faces_folder, group, subject, subfolder
                                    )
                                    os.makedirs(output_path, exist_ok=True)

                                    face_filename = os.path.join(
                                        output_path,
                                        f"{video_name}_frame_{frame_idx}_face_{i}.jpg"
                                    )
                                    cv2.imwrite(face_filename, cropped_face)
                        except Exception as e:
                            print(f"Error detecting/saving face: {e}")

                    frame_idx += 1

                cap.release()

print("Face extraction complete.")

!pip uninstall -y retinaface tensorflow keras
!pip install tensorflow==2.15.0 keras==2.15.0
!pip install git+https://github.com/serengil/retinaface.git