# -*- coding: utf-8 -*-
"""Feature_extraction_per_frame.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GwfGSkHSfH1XCdaNi31nx0fQef_FemPs
"""

import os
import numpy as np
import pickle
from tensorflow.keras.applications import VGG16
from tensorflow.keras.models import Model
from tensorflow.keras.preprocessing import image
from tensorflow.keras.applications.vgg16 import preprocess_input
from tqdm import tqdm

try:
    from google.colab import drive
    drive.mount('/content/drive')
except Exception:
    pass

base_model = VGG16(weights='imagenet', include_top=True)

fc1_model = Model(inputs=base_model.input, outputs=base_model.get_layer("fc1").output)
fc2_model = Model(inputs=base_model.input, outputs=base_model.get_layer("fc2").output)

def extract_fc1_fc2_features(img_path):
    img = image.load_img(img_path, target_size=(224, 224))
    x = image.img_to_array(img)
    x = np.expand_dims(x, axis=0)
    x = preprocess_input(x)

    fc1_features = fc1_model.predict(x, verbose=0)
    fc2_features = fc2_model.predict(x, verbose=0)

    features = np.concatenate([fc1_features, fc2_features], axis=1)
    return features.flatten()

def extract_features_dataset(root_dir, output_pkl="fc_features.pkl"):
    all_features = {}

    for group in ["experimental", "control"]:
        group_path = os.path.join(root_dir, group)
        if not os.path.isdir(group_path):
            continue
        all_features[group] = {}

        for subject in tqdm(os.listdir(group_path), desc=f"{group}"):
            subject_path = os.path.join(group_path, subject)
            if not os.path.isdir(subject_path):
                continue
            all_features[group][subject] = {}

            for segment in os.listdir(subject_path):
                segment_path = os.path.join(subject_path, segment)
                if not os.path.isdir(segment_path):
                    continue
                segment_features = []

                for fname in os.listdir(segment_path):
                    if fname.lower().endswith((".jpg", ".png")):
                        img_path = os.path.join(segment_path, fname)
                        features = extract_fc1_fc2_features(img_path)
                        segment_features.append(features)

                if segment_features:
                    all_features[group][subject][segment] = np.array(segment_features)

    with open(output_pkl, "wb") as f:
        pickle.dump(all_features, f)

    print(f"✅ Features saved to {output_pkl}")
    return all_features

frames = "/content/drive/MyDrive/Project Data/Frames"
features = extract_features_dataset(frames, output_pkl="/content/drive/MyDrive/Project Data/cv_features/fc1_fc2_features_frame.pkl")

